name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: true
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
